language: node_js
dist: bionic
os:
  - linux
  - osx
  - windows
node_js:
  - "10"
  - "12"
  - "14"
deploy:
  provider: npm
  edge: true
  on:
    tags: true
  email: schneefux+npm@schneefux.xyz
  access: private
  registry: https://npm.pkg.github.com/schneefux
