language: node_js
dist: bionic
os:
  - linux
  - osx
  - windows
node_js: "12"
env:
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336/2
  - YARN_GPG=no
script:
  - yarn build
  - yarn test
  - yarn package
deploy:
  provider: releases
  edge: true
  file: parserato-*.zip
  overwrite: true
  on:
    tags: true
jobs:
  include:
    - stage: npm
      script: yarn build
      deploy:
        provider: npm
        edge: true
        on:
          tags: true
        email: schneefux+npm@schneefux.xyz
        access: private
        registry: https://npm.pkg.github.com/schneefux